### PR TITLE
disable offline features

### PR DESCRIPTION
**Pull request by PH-14**
This PR aims at disabling features that should not be used when the user is offline.

### CODE REVIEW

**Comment by MeKHell** [comment]
Wait before merging, this PR might be useless, see mine.

**Comment by MeKHell** [comment]
You can just disable the profile picture button others should work.

**Review by MeKHell — APPROVED** [review]
As far as I am concerned, this PR could be merged. (when the CI passes)
With the new cache that should be merged soon, it is possible to cache locally the collection and to send it to Firebase later. It is also possible to see your followers if you already went to this page. It is up to you to decide if you still want to disable these features.

Disabling the editButton is still required

**Review by MariemBaccari — CHANGES_REQUESTED** [review]

**Review by MariemBaccari — CHANGES_REQUESTED** [review]
It would also be nice to have a toast every time we go in a fragment while we're offline because now there's a huge delay to retrieve data from the cache and it's not immediately clear that we're expecting something

**Review by MariemBaccari — APPROVED** [review]
Looks ok to me now. Feel free to merge as soon as the CI passes.

**Pull request merged**
